//Projects status
export const PROJECTS_FETCHING = 'PROJECTS_FETCHING';
export const PROJECTS_FETCHED = 'PROJECTS_FETCHED';
export const PROJECTS_FETCHING_ERROR = 'PROJECTS_FETCHING_ERROR';
export const PROJECT_CREATED = 'PROJECT_CREATED';
export const PROJECT_DELETED = 'PROJECT_DELETED';
