//Projects status
export const PROJECTS_FETCHING = 'PROJECTS_FETCHING';
export const PROJECTS_FETCHED = 'PROJECTS_FETCHED';
export const PROJECTS_FETCHING_ERROR = 'PROJECTS_FETCHING_ERROR';
export const PROJECT_CREATED = 'PROJECT_CREATED';
export const PROJECT_DELETED = 'PROJECT_DELETED';

//Show/Hide modal
export const SHOW_ADD_PROJECT_MODAL = 'SHOW_ADD_PROJECT_MODAL';
export const HIDE_ADD_PROJECT_MODAL = 'HIDE_ADD_PROJECT_MODAL';

export const SHOW_REMOVE_PROJECT_MODAL = 'SHOW_REMOVE_PROJECT_MODAL';
export const HIDE_REMOVE_PROJECT_MODAL = 'HIDE_REMOVE_PROJECT_MODAL';

export const SHOW_ADD_NEW_TASK_MODAL = 'SHOW_ADD_NEW_TASK_MODAL';
export const HIDE_ADD_NEW_TASK_MODAL = 'HIDE_ADD_NEW_TASK_MODAL';

//Tasks (update, filter)
export const UPDATE_COLUMNS = 'UPDATE_COLUMNS';
export const FILTER_TASKS_BY_NUMBER = 'FILTER_TASKS_BY_NUMBER';
export const FILTER_TASKS_BY_TITLE = 'FILTER_TASKS_BY_TITLE';
export const UPDATE_NUMBER_OF_TASKS = 'UPDATE_NUMBER_OF_TASKS';

//Tasks status
export const TASKS_FETCHING = 'TASKS_FETCHING';
export const TASKS_FETCHED = 'TASKS_FETCHED';
export const TASKS_FETCHING_ERROR = 'TASKS_FETCHING_ERROR';

//Subtasks
export const ADD_SUBTASK = 'ADD_SUBTASK';
export const UPDATE_STATUS_SUBTASK = 'UPDATE_STATUS_SUBTASK';
export const DELETE_SUBTASK = 'DELETE_SUBTASK';
