//Projects status
export const PROJECTS_FETCHING = 'PROJECTS_FETCHING';
export const PROJECTS_FETCHED = 'PROJECTS_FETCHED';
export const PROJECTS_FETCHING_ERROR = 'PROJECTS_FETCHING_ERROR';
export const PROJECT_CREATED = 'PROJECT_CREATED';
export const PROJECT_DELETED = 'PROJECT_DELETED';

//Show/Hide modal
export const SHOW_ADD_PROJECT_MODAL = 'SHOW_ADD_PROJECT_MODAL';
export const HIDE_ADD_PROJECT_MODAL = 'HIDE_ADD_PROJECT_MODAL';

export const SHOW_REMOVE_PROJECT_MODAL = 'SHOW_REMOVE_PROJECT_MODAL';
export const HIDE_REMOVE_PROJECT_MODAL = 'HIDE_REMOVE_PROJECT_MODAL';

//Tasks (update, filter)
export const UPDATE_COLUMNS = 'UPDATE_COLUMNS';
export const FILTER_TASKS_BY_NUMBER = 'FILTER_TASKS_BY_NUMBER';
